### ISSUE TITLE
Thanks + question about automatic refresh

### ISSUE THREAD

**Issue by briochemc** [fredrikekre/LiterateLive.jl#1]
Thank you very much for making this example, this is very helpful and it would have taken me ages to figure out! Running
```
julia --project=docs --color=yes -L docs/live.jl
```
works (almost) perfectly! 😃 

I still have one issue though: the automatic refresh of the browser on saves. (This automatic refresh works on the example in LiveServer.jl's documentation though.) Maybe I missed something? Do you get automatic refresh to work in this repo?

**Comment by fredrikekre** [comment]
> I still have one issue though: the automatic refresh of the browser on saves. 

Yea, doesn't work for me either, not sure if I missed something or if it was a browser problem.

**Comment by fredrikekre** [comment]
https://github.com/fredrikekre/LiterateLive.jl/commit/55805bd95c8f82a66dbfc3d32ae8ad3db07b53c8 should fix the automatic refresh.

**Comment by briochemc** [comment]
Thanks!
